### PR TITLE
Fixing the cache keys to make them relative to the project root

### LINKED ISSUE #11: Cache is storing absolute paths starting from user's root
This means that any time someone runs a new build, the entire mash is re-mashed.

### PR DESCRIPTION
**Pull request by liamegan**
## Description

Resolves the issue with the keys not working cross-machine, as absolute paths are obviously different.

Updated the queue generation to create and use relative file paths.
Updated the file testing to be able to parse relative paths.

Fixes #11

### CODE REVIEW

**Review by marlonmarcello — DISMISSED** [review]
Haven't tested but the updates make sense to me. Just a reminder, we need a changeset to publish the updates before we merge!

**Review by andrewrubin — CHANGES_REQUESTED** [review]
Nice one @liamegan , this is working 🎉 

I think we're nearly there — looks like there's one more update required. When I delete a file, it's still looking for the absolute path from my machine:

```
masher - file /Users/andrewrubin/Desktop/masher-test/src/images/antman-in-a-pikmin-world-2x.png was removed but not found in cache
```

**Comment by liamegan** [comment]
> Nice one @liamegan , this is working 🎉
> 
> I think we're nearly there — looks like there's one more update required. When I delete a file, it's still looking for the absolute path from my machine:
> 
> ```
> masher - file /Users/andrewrubin/Desktop/masher-test/src/images/antman-in-a-pikmin-world-2x.png was removed but not found in cache
> ```

I think I've resolved this now, @andrewrubin, and in the process also #12 (possibly)

**Comment by andrewrubin** [comment]
Still getting that error @liamegan  :(

Attaching a video so you can see the steps I'm taking

https://github.com/wethegit/masher/assets/30575213/fbb696da-4ca5-4bd7-bf74-fcceb3e0e0b0

File: src/delete-files.ts [hunk 1]
```diff
@@ -13,7 +15,8 @@ export function deleteFiles(path: string, cache: Cache) {
     const filesToDelete = cache[path]?.generatedFiles || []
 
     filesToDelete.forEach((d) => {
-      fse.remove(d)
+      d = resolve(d)
+      fse.unlink(d)
```
Comment (marlonmarcello) [inline src/delete-files.ts]: I thnk it'd be good to still use `remove` instead of `unlink`.  
`Unlink` is the native node api to remove a file but it does throw if a file doesn't exist, which can happen here.

Doing a check before deleting works too.

**Review by marlonmarcello — DISMISSED** [review]

**Comment by marlonmarcello** [comment]
> Still getting that error @liamegan :(
> 
> Attaching a video so you can see the steps I'm taking
> 
>  Screen.Recording.2024-02-05.at.11.52.43.AM.mp4

Just to make sure, did you run a `build` before pulling and testing?

**Comment by andrewrubin** [comment]
> Just to make sure, did you run a `build` before pulling and testing?

Yep. Triple checked that 😄

File: src/delete-files.ts (hunk 1 above)
Comment (liamegan) [reply src/delete-files.ts]: @marlonmarcello I moved to unlink as I thought it was the more native file function and remove wasn't working.

**Comment by liamegan** [comment]
> Still getting that error @liamegan :(
> 
> Attaching a video so you can see the steps I'm taking
> 
>  Screen.Recording.2024-02-05.at.11.52.43.AM.mp4

Ah ok, I was testing with running, not watching, and I can replicate the error now. Thanks for the clarification!

**Comment by liamegan** [comment]
Alright, I think that's all good to go now.

**Review by andrewrubin — APPROVED** [review]
It's a thing of beauty, thanks!

**Comment by liamegan** [comment]
@andrewrubin @marlonmarcello I'll let y'all merge this whenever you're ready to do so.

File: src/delete-files.ts (hunk 1 above)
Comment (liamegan) [reply src/delete-files.ts]: @marlonmarcello I've resolved this with an `fse.existsSync`

**Comment by marlonmarcello** [comment]
Thanks @liamegan !
